### ISSUE TITLE
filenames become URLs

### ISSUE THREAD

**Issue by mixmix** [peachcloud/peach-devdocs#2]
hey @mycognosist you may have realised this already, but when you build this project, the files in `/src` get mapped into html files in `/book` with the same names, and these essentially become URIs for particular pages.

My recommendation would be to change the names from chapter details (which you may want to change) to semantic descriptions, because this will mean you're less likely to get tripped up / trip other people up who link to the docs <3

**Comment by mixmix** [comment]
Just did a quick test and discovered you can happily use folders for nesting / collecting related things e.g. : 

```
- [Introduction](./introduction.md)
- [Hardware](./hardware/index.md)
  - [Requirements](./hardware/requirements.md)
  - [GPIO Pinout](./hardware/gpio_pinout.md)
  - [Physical Interface](./hardware/physical_interface.md)
```

**Comment by mycognosist** [comment]
@mixmix ahh yeah the `chapter_x_x.md` naming was giving me nightmares :laughing:  Thanks for the reminder! I think the semantic naming approach using folders is the way to go. I've updated the repo accordingly.

**Comment by mixmix** [comment]
hooray!

It was fun to be able to contribute to this even if I don't understand the project details yet. Excited to learn more in the future
